/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.GridLayout;
import java.awt.Image;
import java.io.IOException;
import java.sql.CallableStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Box;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import oracle.jdbc.OraclePreparedStatement;
import oracle.jdbc.OracleResultSet;
import oracle.ord.im.OrdImage;
import oracle.sql.ARRAY;
import oracle.sql.STRUCT;
import utils.ConnexionUtils;

/**
 *
 * @author aj205896
 */
public class DlgAffichePersonne extends javax.swing.JFrame {

    private int id;
    private Image photo;
    
    public DlgAffichePersonne(int id) {
        initComponents();
        this.id = id;
        this.initialiserEnqueteur();
    }
    
    private void initialiserEnqueteur()
    {
        try 
        {
            OraclePreparedStatement stmt = (OraclePreparedStatement)ConnexionUtils.getInstance().prepareStatement("SELECT * FROM bdm_personne WHERE id=?");
            stmt.setInt(1, this.id);
            OracleResultSet rs = (OracleResultSet)stmt.executeQuery();
            rs.next();
            //Récupération des informations de la personne
            this.Nom.setText(rs.getString("NOM"));
            this.Prenom.setText(rs.getString("PRENOM"));
            //Récupération de l'adresse
            STRUCT adresse = rs.getSTRUCT("ADRESSE");
            Object[] adresse_attributs = adresse.getAttributes();
            this.NumeroRue.setText(adresse_attributs[0].toString());
            this.NomRue.setText(adresse_attributs[1].toString());
            this.Ville.setText(adresse_attributs[2].toString());
            //Récupération des numéros de téléphone
            ARRAY telephone = rs.getARRAY("TELEPHONE");
            Object[] tel = (Object[])telephone.getArray();
            this.Telephone1.setText(((STRUCT)tel[0]).getAttributes()[0].toString());
            this.Telephone2.setText(((STRUCT)tel[1]).getAttributes()[0].toString());
            //Récupération de la photo
            OrdImage img = (OrdImage)rs.getORAData("PHOTO", OrdImage.getORADataFactory());
            String fichier = "temp/personne/"+this.id;
            img.getDataInFile(fichier);
            this.photo = this.Photo.getToolkit().getImage(fichier);
            affichePhoto();
            rs.close();
            stmt.close();
        } 
        catch (SQLException | IOException ex) 
        {
            Logger.getLogger(DlgAffichePersonne.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void affichePhoto()
    {
        Graphics2D g = (Graphics2D)this.Photo.getGraphics();
        Double scaleWidth = this.Photo.getWidth()/new Double(this.photo.getWidth(null));
	Double scaleHeight = this.Photo.getHeight()/new Double(this.photo.getHeight(null));
        if (scaleWidth>scaleHeight)
            scaleWidth = scaleHeight;
        else
            scaleHeight = scaleWidth;
        int x = (int)((this.Photo.getWidth() - (this.photo.getWidth(null)*scaleWidth)) / 2);
        int y = (int)((this.Photo.getHeight() - (this.photo.getHeight(null)*scaleHeight)) / 2);
        g.translate(x, y);
        g.scale(scaleWidth, scaleHeight);
        g.drawImage(this.photo, 0, 0, null);
    }
    
    public void paint(Graphics g)
    {
        super.paint(g);
        if(this.photo!=null)
            this.affichePhoto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Nom = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Prenom = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ModifierAdresse = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        NumeroRue = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        NomRue = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Ville = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        Photo = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        Telephone1 = new javax.swing.JLabel();
        ModifierTelephone1 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        Telephone2 = new javax.swing.JLabel();
        ModifierTelephone2 = new javax.swing.JButton();
        SupprimerEnqueteur = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(230, 215, 184));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 280));
        jPanel1.setLayout(new java.awt.GridLayout(1, 2));

        jPanel2.setBackground(new java.awt.Color(226, 220, 207));
        jPanel2.setPreferredSize(new java.awt.Dimension(330, 100));
        jPanel2.setLayout(new java.awt.GridLayout(6, 2));

        jLabel3.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel3.setText("Nom :");
        jPanel2.add(jLabel3);

        Nom.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jPanel2.add(Nom);

        jLabel5.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel5.setText("Prenom :");
        jPanel2.add(jLabel5);

        Prenom.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jPanel2.add(Prenom);

        jLabel2.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel2.setText("Adresse");
        jPanel2.add(jLabel2);

        ModifierAdresse.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        ModifierAdresse.setText("Modifier");
        ModifierAdresse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifierAdresseActionPerformed(evt);
            }
        });
        jPanel2.add(ModifierAdresse);

        jLabel4.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel4.setText("Numéro de rue :");
        jLabel4.setPreferredSize(new java.awt.Dimension(150, 21));
        jPanel2.add(jLabel4);

        NumeroRue.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jPanel2.add(NumeroRue);

        jLabel7.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel7.setText("Rue :");
        jPanel2.add(jLabel7);

        NomRue.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jPanel2.add(NomRue);

        jLabel9.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel9.setText("Ville :");
        jPanel2.add(jLabel9);

        Ville.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jPanel2.add(Ville);

        jPanel1.add(jPanel2);

        jPanel5.setBackground(new java.awt.Color(226, 220, 207));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(226, 220, 207));
        jPanel3.setPreferredSize(new java.awt.Dimension(0, 470));
        jPanel3.setLayout(new java.awt.GridLayout(1, 1));

        Photo.setBackground(new java.awt.Color(226, 220, 207));
        Photo.setPreferredSize(new java.awt.Dimension(0, 370));

        javax.swing.GroupLayout PhotoLayout = new javax.swing.GroupLayout(Photo);
        Photo.setLayout(PhotoLayout);
        PhotoLayout.setHorizontalGroup(
            PhotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );
        PhotoLayout.setVerticalGroup(
            PhotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel3.add(Photo);

        jPanel5.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel5);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel4.setLayout(new java.awt.GridLayout(3, 1));

        jPanel7.setBackground(new java.awt.Color(226, 220, 207));
        jPanel7.setLayout(new java.awt.GridLayout(1, 3));

        jLabel6.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel6.setText("Téléphone 1 :");
        jLabel6.setPreferredSize(new java.awt.Dimension(143, 50));
        jPanel7.add(jLabel6);

        Telephone1.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jPanel7.add(Telephone1);

        ModifierTelephone1.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        ModifierTelephone1.setText("Modifier");
        ModifierTelephone1.setPreferredSize(new java.awt.Dimension(121, 40));
        ModifierTelephone1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifierTelephone1ActionPerformed(evt);
            }
        });
        jPanel7.add(ModifierTelephone1);

        jPanel4.add(jPanel7);

        jPanel8.setBackground(new java.awt.Color(226, 220, 207));
        jPanel8.setLayout(new java.awt.GridLayout(1, 3));

        jLabel10.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel10.setText("Téléphone 2 :");
        jPanel8.add(jLabel10);

        Telephone2.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jPanel8.add(Telephone2);

        ModifierTelephone2.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        ModifierTelephone2.setText("Modifier");
        ModifierTelephone2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifierTelephone2ActionPerformed(evt);
            }
        });
        jPanel8.add(ModifierTelephone2);

        jPanel4.add(jPanel8);

        SupprimerEnqueteur.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        SupprimerEnqueteur.setText("Supprimer");
        SupprimerEnqueteur.setPreferredSize(new java.awt.Dimension(131, 40));
        SupprimerEnqueteur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupprimerEnqueteurActionPerformed(evt);
            }
        });
        jPanel4.add(SupprimerEnqueteur);

        getContentPane().add(jPanel4, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ModifierAdresseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifierAdresseActionPerformed
        //JTextField modification de l'adresse
        JTextField num = new JTextField();
        num.setSize(100,20);
        JTextField rue = new JTextField();
        rue.setSize(100,20);
        JTextField ville = new JTextField();
        ville.setSize(100,20);
        JPanel jp = new JPanel();
        jp.setLayout(new GridLayout(3,3));
        jp.add(new JLabel("Numero :"));
        jp.add(num);
        jp.add(Box.createHorizontalStrut(15)); // a spacer
        jp.add(new JLabel("Rue :"));
        jp.add(rue);
        jp.add(Box.createHorizontalStrut(15)); // a spacer
        jp.add(new JLabel("Ville :"));
        jp.add(ville);
        JOptionPane jop = new JOptionPane();
        int adresse;
        //Vérification adresse
        boolean continuer = true;
        boolean valide = true;
        String mes = "Modifier adresse: ";
        while(continuer)
        {
            adresse = jop.showConfirmDialog(null, jp, mes, JOptionPane.OK_CANCEL_OPTION);
            if(adresse==JOptionPane.CANCEL_OPTION)
            {
                continuer=false;
            }
            else if(num.getText().equals("") || rue.getText().equals("") || ville.getText().equals(""))
            {
                mes="Veuillez entrer une adresse valide";
                valide=false;
            }
            else
            {

                try{
                    Integer.parseInt(num.getText());
                    valide=true;
                }
                catch(NumberFormatException e)
                {
                    mes="Veuillez entrer un numéro valide";
                    valide=false;

                }
                if(valide && Integer.parseInt(num.getText())>=0)
                {

                    try {
                        String sql = "{call majPersonneAdresse(?, ?, ?, ?)}";
                        CallableStatement stmt = ConnexionUtils.getInstance().prepareCall(sql);
                        ConnexionUtils.getInstance().setAutoCommit(false);
                        stmt.setInt(1, this.id);
                        stmt.setInt(2, Integer.parseInt(num.getText()));
                        stmt.setString(3, rue.getText());
                        stmt.setString(4, ville.getText());
                        stmt.execute();
                        ConnexionUtils.getInstance().commit();
                        stmt.close();
                        ConnexionUtils.getInstance().setAutoCommit(true);
                        NumeroRue.setText(num.getText());
                        NomRue.setText(rue.getText());
                        Ville.setText(ville.getText());
                        continuer=false;
                    } catch (SQLException ex) {
                        Logger.getLogger(DlgAffichePersonne.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }
            }

        }
    }//GEN-LAST:event_ModifierAdresseActionPerformed

    private void ModifierTelephone1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifierTelephone1ActionPerformed
        //Modification du numéro de téléphone 1
        JOptionPane jop = new JOptionPane();
        String telephone1;
        //Vérification numéro
        boolean continuer = true;
        boolean valide = true;
        String mes = "Modifier Téléphone 1 : ";
        while(continuer)
        {
            telephone1 = jop.showInputDialog(null, mes, "Modifier", JOptionPane.QUESTION_MESSAGE);
            if(telephone1==null)
            {
                continuer=false;
            }
            else if(!telephone1.equals(""))
            {
                try{
                    Long.parseLong(telephone1);
                    valide=true;
                }
                catch(NumberFormatException e)
                {
                    mes="Veuillez entrer un numéro de téléphone valide";
                    valide=false;

                }
                if(valide && Long.parseLong(telephone1)>=0)
                {

                    try {
                        String sql = "{call majPersonneTelephone(?, ?, ?)}";
                        CallableStatement stmt = ConnexionUtils.getInstance().prepareCall(sql);
                        ConnexionUtils.getInstance().setAutoCommit(false);
                        stmt.setInt(1, this.id);
                        stmt.setInt(2, 1);
                        stmt.setString(3, telephone1);
                        stmt.execute();
                        ConnexionUtils.getInstance().commit();
                        stmt.close();
                        ConnexionUtils.getInstance().setAutoCommit(true);
                        Telephone1.setText(telephone1);
                        continuer=false;                }
                    catch (SQLException ex)
                    {
                        Logger.getLogger(DlgAffichePersonne.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }

        }
    }//GEN-LAST:event_ModifierTelephone1ActionPerformed

    private void ModifierTelephone2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifierTelephone2ActionPerformed
        //Modification du numéro de téléphone 2
        JOptionPane jop = new JOptionPane();
        String telephone2;
        //Vérification numéro
        boolean continuer = true;
        boolean valide = true;
        String mes = "Modifier Téléphone 2 : ";
        while(continuer)
        {
            telephone2 = jop.showInputDialog(null, mes, "Modifier", JOptionPane.QUESTION_MESSAGE);
            if(telephone2==null)
            {
                continuer=false;
            }
            else if(!telephone2.equals(""))
            {
                try{
                    Long.parseLong(telephone2);
                    valide=true;
                }
                catch(NumberFormatException e)
                {
                    mes="Veuillez rentrer un numéro de téléphone valide";
                    valide=false;

                }
                if(valide && Long.parseLong(telephone2)>=0)
                {

                    try {
                        String sql = "{call majPersonneTelephone(?, ?, ?)}";
                        CallableStatement stmt = ConnexionUtils.getInstance().prepareCall(sql);
                        ConnexionUtils.getInstance().setAutoCommit(false);
                        stmt.setInt(1, this.id);
                        stmt.setInt(2, 2);
                        stmt.setString(3, telephone2);
                        stmt.execute();
                        ConnexionUtils.getInstance().commit();
                        stmt.close();
                        ConnexionUtils.getInstance().setAutoCommit(true);
                        Telephone2.setText(telephone2);
                        continuer=false;                }
                    catch (SQLException ex)
                    {
                        Logger.getLogger(DlgAffichePersonne.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }

        }
    }//GEN-LAST:event_ModifierTelephone2ActionPerformed

    private void SupprimerEnqueteurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupprimerEnqueteurActionPerformed
        try
        {
            int id = this.id;
            ConnexionUtils.getInstance().setAutoCommit(false);
            //Supression
            OraclePreparedStatement stmt = (OraclePreparedStatement)ConnexionUtils.getInstance().prepareStatement("DELETE FROM bdm_personne WHERE id="+id+"");
            stmt.executeQuery();
            ConnexionUtils.getInstance().commit();
            stmt.close();
            ConnexionUtils.getInstance().setAutoCommit(true);
        }
        catch (SQLException ex)
        {
            Logger.getLogger(DlgAffichePersonne.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);

    }//GEN-LAST:event_SupprimerEnqueteurActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgAffichePersonne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgAffichePersonne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgAffichePersonne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgAffichePersonne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ModifierAdresse;
    private javax.swing.JButton ModifierTelephone1;
    private javax.swing.JButton ModifierTelephone2;
    private javax.swing.JLabel Nom;
    private javax.swing.JLabel NomRue;
    private javax.swing.JLabel NumeroRue;
    private javax.swing.JPanel Photo;
    private javax.swing.JLabel Prenom;
    private javax.swing.JButton SupprimerEnqueteur;
    private javax.swing.JLabel Telephone1;
    private javax.swing.JLabel Telephone2;
    private javax.swing.JLabel Ville;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    // End of variables declaration//GEN-END:variables
}
