/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.awt.*;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import oracle.jdbc.*;
import oracle.ord.im.OrdImage;
import oracle.sql.*;
import utils.ConnexionUtils;

/**
 *
 * @author Annabelle
 */
public class DlgAfficheEnqueteur extends javax.swing.JFrame {
    
    private int id;
    private Image photo;
    
    public DlgAfficheEnqueteur(int id) {
        initComponents();
        this.id = id;
        this.initialiserEnqueteur();
    }

    private void initialiserEnqueteur()
    {
        try 
        {
            OraclePreparedStatement stmt = (OraclePreparedStatement)ConnexionUtils.getInstance().prepareStatement("SELECT * FROM bdm_enqueteur WHERE id=?");
            stmt.setInt(1, this.id);
            OracleResultSet rs = (OracleResultSet)stmt.executeQuery();
            rs.next();
            //Récupération des informations de l'enquêteur
            this.Badge.setText(rs.getString("BADGE"));
            this.Nom.setText(rs.getString("NOM"));
            this.Prenom.setText(rs.getString("PRENOM"));
            //Récupération de l'adresse
            STRUCT adresse = rs.getSTRUCT("ADRESSE");
            Object[] adresse_attributs = adresse.getAttributes();
            this.NumeroRue.setText(adresse_attributs[0].toString());
            this.NomRue.setText(adresse_attributs[1].toString());
            this.Ville.setText(adresse_attributs[2].toString());
            //Récupération des numéros de téléphone
            ARRAY telephone = rs.getARRAY("TELEPHONE");
            Object[] tel = (Object[])telephone.getArray();
            this.Telephone1.setText(((STRUCT)tel[0]).getAttributes()[0].toString());
            this.Telephone2.setText(((STRUCT)tel[1]).getAttributes()[0].toString());
            //Récupération de la photo
            OrdImage img = (OrdImage)rs.getORAData("PHOTO", OrdImage.getORADataFactory());
            String fichier = "temp/"+this.id;
            img.getDataInFile(fichier);
            this.photo = this.Photo.getToolkit().getImage(fichier);
            affichePhoto();
            rs.close();
            stmt.close();
        } 
        catch (SQLException | IOException ex) 
        {
            Logger.getLogger(DlgAfficheEnqueteur.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void affichePhoto()
    {
        Graphics g = this.Photo.getGraphics();
        g.drawImage(this.photo, 0, 0, this.Photo.getWidth(), this.Photo.getHeight(), this);
    }
    
    public void paint(Graphics g)
    {
        super.paint(g);
        if(this.photo!=null)
            this.affichePhoto();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Badge = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Nom = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Prenom = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ModifierAdresse = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        NumeroRue = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        NomRue = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Ville = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        Photo = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        Telephone1 = new javax.swing.JLabel();
        ModifierTelephone1 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        Telephone2 = new javax.swing.JLabel();
        ModifierTelephone2 = new javax.swing.JButton();
        SupprimerEnqueteur = new javax.swing.JButton();

        setTitle("Enquêteur");
        setPreferredSize(new java.awt.Dimension(900, 700));
        getContentPane().setLayout(new java.awt.GridLayout(1, 2));

        jPanel1.setBackground(new java.awt.Color(230, 215, 184));
        jPanel1.setLayout(new java.awt.GridLayout(1, 2));

        jPanel2.setBackground(new java.awt.Color(226, 220, 207));
        jPanel2.setLayout(new java.awt.GridLayout(7, 2));

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel1.setText("Badge :");
        jPanel2.add(jLabel1);

        Badge.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jPanel2.add(Badge);

        jLabel3.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel3.setText("Nom :");
        jPanel2.add(jLabel3);

        Nom.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jPanel2.add(Nom);

        jLabel5.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel5.setText("Prenom :");
        jPanel2.add(jLabel5);

        Prenom.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jPanel2.add(Prenom);

        jLabel2.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel2.setText("Adresse");
        jPanel2.add(jLabel2);

        ModifierAdresse.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        ModifierAdresse.setText("Modifier");
        ModifierAdresse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifierAdresseActionPerformed(evt);
            }
        });
        jPanel2.add(ModifierAdresse);

        jLabel4.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel4.setText("Numéro de rue :");
        jPanel2.add(jLabel4);

        NumeroRue.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jPanel2.add(NumeroRue);

        jLabel7.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel7.setText("Rue :");
        jPanel2.add(jLabel7);

        NomRue.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jPanel2.add(NomRue);

        jLabel9.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel9.setText("Ville :");
        jPanel2.add(jLabel9);

        Ville.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jPanel2.add(Ville);

        jPanel1.add(jPanel2);

        jPanel5.setBackground(new java.awt.Color(226, 220, 207));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(226, 220, 207));
        jPanel3.setLayout(new java.awt.GridLayout(1, 1));

        Photo.setBackground(new java.awt.Color(226, 220, 207));
        Photo.setPreferredSize(new java.awt.Dimension(0, 570));

        javax.swing.GroupLayout PhotoLayout = new javax.swing.GroupLayout(Photo);
        Photo.setLayout(PhotoLayout);
        PhotoLayout.setHorizontalGroup(
            PhotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PhotoLayout.setVerticalGroup(
            PhotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel3.add(Photo);

        jPanel5.add(jPanel3, java.awt.BorderLayout.NORTH);

        jPanel6.setLayout(new java.awt.GridLayout(3, 1));

        jPanel7.setBackground(new java.awt.Color(226, 220, 207));
        jPanel7.setLayout(new java.awt.GridLayout(1, 3));

        jLabel6.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel6.setText("Téléphone 1 :");
        jPanel7.add(jLabel6);

        Telephone1.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jPanel7.add(Telephone1);

        ModifierTelephone1.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        ModifierTelephone1.setText("Modifier");
        ModifierTelephone1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifierTelephone1ActionPerformed(evt);
            }
        });
        jPanel7.add(ModifierTelephone1);

        jPanel6.add(jPanel7);

        jPanel8.setBackground(new java.awt.Color(226, 220, 207));
        jPanel8.setLayout(new java.awt.GridLayout(1, 3));

        jLabel10.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel10.setText("Téléphone 2 :");
        jPanel8.add(jLabel10);

        Telephone2.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jPanel8.add(Telephone2);

        ModifierTelephone2.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        ModifierTelephone2.setText("Modifier");
        ModifierTelephone2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifierTelephone2ActionPerformed(evt);
            }
        });
        jPanel8.add(ModifierTelephone2);

        jPanel6.add(jPanel8);

        SupprimerEnqueteur.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        SupprimerEnqueteur.setText("Supprimer");
        SupprimerEnqueteur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupprimerEnqueteurActionPerformed(evt);
            }
        });
        jPanel6.add(SupprimerEnqueteur);

        jPanel5.add(jPanel6, java.awt.BorderLayout.SOUTH);

        jPanel1.add(jPanel5);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ModifierTelephone1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifierTelephone1ActionPerformed
        
    }//GEN-LAST:event_ModifierTelephone1ActionPerformed

    private void ModifierTelephone2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifierTelephone2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModifierTelephone2ActionPerformed

    private void ModifierAdresseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifierAdresseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModifierAdresseActionPerformed

    private void SupprimerEnqueteurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupprimerEnqueteurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SupprimerEnqueteurActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgAfficheEnqueteur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgAfficheEnqueteur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgAfficheEnqueteur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgAfficheEnqueteur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Badge;
    private javax.swing.JButton ModifierAdresse;
    private javax.swing.JButton ModifierTelephone1;
    private javax.swing.JButton ModifierTelephone2;
    private javax.swing.JLabel Nom;
    private javax.swing.JLabel NomRue;
    private javax.swing.JLabel NumeroRue;
    private javax.swing.JPanel Photo;
    private javax.swing.JLabel Prenom;
    private javax.swing.JButton SupprimerEnqueteur;
    private javax.swing.JLabel Telephone1;
    private javax.swing.JLabel Telephone2;
    private javax.swing.JLabel Ville;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    // End of variables declaration//GEN-END:variables
}
