/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.awt.Graphics;
import java.awt.Image;
import java.io.IOException;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import oracle.jdbc.OraclePreparedStatement;
import oracle.jdbc.OracleResultSet;
import oracle.ord.im.OrdImage;
import oracle.sql.ARRAY;
import oracle.sql.STRUCT;
import utils.ConnexionUtils;

/**
 *
 * @author ag092850
 */
public class DlgAffichePreuveImage extends javax.swing.JFrame {
    private int idE;
    private Image image;
    private List<Image> preuves;
    /**
     * Creates new form DlgAffichePreuveImage
     */
    public DlgAffichePreuveImage(int idE) {
        initComponents();
        this.idE = idE;
    }

    private void initialiserEnqueteur()
    {
        try 
        {
            OraclePreparedStatement stmt = (OraclePreparedStatement)ConnexionUtils.getInstance().prepareStatement("SELECT id, image FROM bdm_preuve_image WHERE DEREF(enqueteP).id=? ORDER BY id");
            stmt.setInt(1, this.idE);
            OracleResultSet rs = (OracleResultSet)stmt.executeQuery();
            while(rs.next())
            {
                //Récupération de la photo
                OrdImage img = (OrdImage)rs.getORAData("PHOTO", OrdImage.getORADataFactory());
                String fichier = "temp/image/"+rs.getInt("ID");
                img.getDataInFile(fichier);
                this.preuves.add(this.Image.getToolkit().getImage(fichier));
            }
            this.image = this.preuves.get(0);
            afficheImage();
            rs.close();
            stmt.close();
        } 
        catch (SQLException | IOException ex) 
        {
            Logger.getLogger(DlgAfficheEnqueteur.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void afficheImage()
    {
        Graphics g = this.Image.getGraphics();
        g.drawImage(this.image, 0, 0, this.Image.getWidth(), this.Image.getHeight(), this);
    }
    
    public void paint(Graphics g)
    {
        super.paint(g);
        if(this.image!=null)
            this.afficheImage();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Precedent = new javax.swing.JButton();
        Annuler = new javax.swing.JButton();
        Suivant = new javax.swing.JButton();
        Image = new javax.swing.JPanel();

        jPanel1.setLayout(new java.awt.GridLayout());

        Precedent.setText("<");
        jPanel1.add(Precedent);

        Annuler.setText("Retour");
        Annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnulerActionPerformed(evt);
            }
        });
        jPanel1.add(Annuler);

        Suivant.setText(">");
        jPanel1.add(Suivant);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout ImageLayout = new javax.swing.GroupLayout(Image);
        Image.setLayout(ImageLayout);
        ImageLayout.setHorizontalGroup(
            ImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 415, Short.MAX_VALUE)
        );
        ImageLayout.setVerticalGroup(
            ImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 275, Short.MAX_VALUE)
        );

        getContentPane().add(Image, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnulerActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_AnnulerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgAffichePreuveImage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgAffichePreuveImage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgAffichePreuveImage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgAffichePreuveImage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Annuler;
    private javax.swing.JPanel Image;
    private javax.swing.JButton Precedent;
    private javax.swing.JButton Suivant;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
