/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.sql.*;
import java.util.logging.*;
import oracle.jdbc.*;
import oracle.sql.*;
import utils.ConnexionUtils;
/**
 *
 * @author Annabelle
 */
public class DlgCommissariat extends javax.swing.JFrame {

    private String numeroRue;
    private String rue;
    private String ville;
    private String telephone;
    private StructDescriptor dscrAdresse;
    private StructDescriptor dscrTelephone;
    
    public DlgCommissariat() {
        initComponents();
        this.chargerCommissariat();
    }

    private void chargerCommissariat()
    {
        try 
        {
            int idC = 1;
            PreparedStatement stmt = ConnexionUtils.getInstance().prepareStatement("SELECT * FROM bdm_commissariat WHERE numeroCo=?");
            stmt.setInt(1, idC);
            OracleResultSet rs = (OracleResultSet)stmt.executeQuery();
            rs.next();
            //Récupération de l'adresse
            STRUCT adresse = rs.getSTRUCT("adresse");
            this.dscrAdresse = adresse.getDescriptor();
            Object[] adresse_attributs = adresse.getAttributes();
            this.numeroRue = adresse_attributs[0].toString();
            this.rue = adresse_attributs[1].toString();
            this.ville = adresse_attributs[2].toString();
            //Récupération du téléphone
            STRUCT telephone = rs.getSTRUCT("telC");
            this.dscrTelephone = telephone.getDescriptor();
            this.telephone = telephone.getAttributes()[0].toString();
            //Fermeture du OracleResultSet
            rs.close();
            //Ecriture des informations
            this.NumeroRue.setText(this.numeroRue);
            this.Rue.setText(this.rue);
            this.Ville.setText(this.ville);
            this.Telephone.setText(this.telephone);
        } 
        catch (SQLException ex) 
        {
            Logger.getLogger(DlgCommissariat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        NumeroRue = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Rue = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Ville = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Telephone = new javax.swing.JTextField();
        Annuler = new javax.swing.JButton();
        Valider = new javax.swing.JButton();

        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setLayout(new java.awt.GridLayout(5, 2));

        jLabel1.setText("Numéro de rue");
        jPanel1.add(jLabel1);
        jPanel1.add(NumeroRue);

        jLabel2.setText("Rue");
        jPanel1.add(jLabel2);
        jPanel1.add(Rue);

        jLabel3.setText("Ville");
        jPanel1.add(jLabel3);
        jPanel1.add(Ville);

        jLabel4.setText("Téléphone");
        jPanel1.add(jLabel4);
        jPanel1.add(Telephone);

        Annuler.setText("Annuler");
        Annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnulerActionPerformed(evt);
            }
        });
        jPanel1.add(Annuler);

        Valider.setText("Valider");
        Valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValiderActionPerformed(evt);
            }
        });
        jPanel1.add(Valider);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnulerActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_AnnulerActionPerformed

    private void ValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValiderActionPerformed
        String modifNumeroRue = this.NumeroRue.getText();
        String modifRue = this.Rue.getText();
        String modifVille = this.Ville.getText();
        String modifTelephone = this.Telephone.getText();
        
        if(!modifNumeroRue.equals(this.numeroRue) || !modifRue.equals(this.rue) || 
                !modifVille.equals(this.ville) || !modifTelephone.equals(this.telephone))
        {
            //TODO: appel d'une procédure SQL pour la MAJ
            /*
            try 
            {
                //Construction du STRUCT adresse
                Object[] adresse_attributs = new Object[3];
                adresse_attributs[0] = modifNumeroRue;
                adresse_attributs[1] = modifRue;
                adresse_attributs[2] = modifVille;
                STRUCT adresse = new STRUCT(this.dscrAdresse, ConnexionUtils.getInstance(), adresse_attributs);
                //Construction du STRUCT telephone
                Object[] telephone_attributs = new Object[1];
                adresse_attributs[0] = modifTelephone;
                STRUCT telC = new STRUCT(this.dscrTelephone, ConnexionUtils.getInstance(), telephone_attributs);
                //Construction de la requête
                OraclePreparedStatement stmt = (OraclePreparedStatement)ConnexionUtils.getInstance().prepareStatement("UPDATE bdm_commissariat SET adresse =?, telC=? WHERE numeroCo=?");
                stmt.setSTRUCT(1, adresse);
                stmt.setSTRUCT(2, telC);
                stmt.executeQuery();
                System.out.println("Mise à jour effectuée !");
            } 
            catch (SQLException ex) 
            {
                Logger.getLogger(DlgCommissariat.class.getName()).log(Level.SEVERE, null, ex);
            }
            */
        }
        this.setVisible(false);
    }//GEN-LAST:event_ValiderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgCommissariat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgCommissariat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgCommissariat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgCommissariat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DlgCommissariat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Annuler;
    private javax.swing.JTextField NumeroRue;
    private javax.swing.JTextField Rue;
    private javax.swing.JTextField Telephone;
    private javax.swing.JButton Valider;
    private javax.swing.JTextField Ville;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
