/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.awt.Font;
import java.awt.GridLayout;
import java.sql.CallableStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.SwingConstants;
import oracle.jdbc.OraclePreparedStatement;
import oracle.jdbc.OracleResultSet;
import utils.ConnexionUtils;

/**
 *
 * @author Annabelle
 */
public class DlgResultatRechercheTemoignages extends javax.swing.JFrame
{
    private int idE;
    private String recherche;
    /**
     * Creates new form DlgResultatRechercheTemoignages
     */
    public DlgResultatRechercheTemoignages(int idE, String recherche)
    {
        initComponents();
        this.idE = idE;
        this.recherche = recherche;
        this.lancerRecherche();
    }

    private void lancerRecherche()
    {
        try
        {
            this.Temoignages.removeAll();
            //Récupération des informations de l'enquête
            OraclePreparedStatement stmt = (OraclePreparedStatement)ConnexionUtils.getInstance().prepareStatement("SELECT nom FROM bdm_enquete WHERE id=?");
            stmt.setInt(1, this.idE);
            OracleResultSet rs = (OracleResultSet)stmt.executeQuery();
            rs.next();
            this.NomEnquete.setText(rs.getString("NOM"));
            //Récupération des témoignages correspondants à la recherche
            stmt = (OraclePreparedStatement)ConnexionUtils.getInstance().prepareStatement("SELECT id, contenu, DEREF(crimeT).id FROM bdm_temoignage "
                    + "WHERE CONTAINS(contenu, ?)>0 AND DEREF(DEREF(crimeT).enqueteC).id<>? ORDER BY CONTAINS(contenu, ?) DESC");
            stmt.setString(1, this.recherche);
            stmt.setInt(2, this.idE);
            stmt.setString(3, this.recherche);
            rs = (OracleResultSet)stmt.executeQuery();
            int gridNbLignes = 0;
            Font fonte = new Font("Courier",Font.PLAIN,14);
            while(rs.next())
            {
                gridNbLignes++;
                JScrollPane jsp = new JScrollPane();
                JTextArea jta = new JTextArea();
                JButton jb = new JButton();
                jta.setText(rs.getString("CONTENU"));
                jta.setEditable(false);
                jsp.setViewportView(jta);
                jb.setName(""+rs.getInt("ID")+"_"+rs.getInt("DEREF(crimeT).id"));
                jb.setFont(fonte);
                jb.setText("Lier le crime correspondant à ce témoignage à l'enquête");
                
                //Ajout du listener
                jb.addActionListener(new java.awt.event.ActionListener()
                {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        changerEnqueteDuCrime(evt);
                    }
                });
                
                this.Temoignages.add(jsp);
                this.Temoignages.add(jb);
            }
            if(gridNbLignes>0)
                this.Temoignages.setLayout(new GridLayout(gridNbLignes, 2));
            else
            {
                this.Temoignages.setLayout(new GridLayout(1, 1));
                JLabel jl = new JLabel("Aucune correspondance trouvée.");
                jl.setHorizontalAlignment(JLabel.CENTER);
                this.Temoignages.add(jl);
            }
        } 
        catch (SQLException ex)
        {
            Logger.getLogger(DlgResultatRechercheTemoignages.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setSize(this.getWidth()-1, this.getHeight()-1);
        this.setSize(this.getWidth()+1, this.getHeight()+1);
    }
    
    private void changerEnqueteDuCrime(java.awt.event.ActionEvent evt)
    {
        try
        {
            JButton jb = (JButton)evt.getSource();
            int idC = Integer.parseInt(jb.getName().split("_")[1]);
            CallableStatement stmt = ConnexionUtils.getInstance().prepareCall("{call changerEnqueteDuCrime(?, ?)}");
            stmt.setInt(1, idC);
            stmt.setInt(2, this.idE);
            stmt.execute();
            stmt.close();
            this.lancerRecherche();
        } 
        catch (SQLException ex)
        {
            Logger.getLogger(DlgResultatRechercheTemoignages.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        NomEnquete = new javax.swing.JLabel();
        Temoignages = new javax.swing.JPanel();

        setBackground(new java.awt.Color(226, 220, 207));

        jPanel1.setBackground(new java.awt.Color(226, 220, 207));
        jPanel1.setLayout(new java.awt.GridLayout());

        NomEnquete.setBackground(new java.awt.Color(226, 220, 207));
        NomEnquete.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        NomEnquete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NomEnquete.setText("NomEnquete");
        NomEnquete.setPreferredSize(new java.awt.Dimension(110, 40));
        jPanel1.add(NomEnquete);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        Temoignages.setBackground(new java.awt.Color(226, 220, 207));
        Temoignages.setPreferredSize(new java.awt.Dimension(500, 400));

        javax.swing.GroupLayout TemoignagesLayout = new javax.swing.GroupLayout(Temoignages);
        Temoignages.setLayout(TemoignagesLayout);
        TemoignagesLayout.setHorizontalGroup(
            TemoignagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        TemoignagesLayout.setVerticalGroup(
            TemoignagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(Temoignages, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(DlgResultatRechercheTemoignages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(DlgResultatRechercheTemoignages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(DlgResultatRechercheTemoignages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(DlgResultatRechercheTemoignages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NomEnquete;
    private javax.swing.JPanel Temoignages;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
