/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import javax.swing.JOptionPane;

/**
 *
 * @author Annabelle
 */
public class DlgRechercheTemoignages extends javax.swing.JFrame
{
    private String recherche;
    private int regroupement;
    private int regroupementEnAttente;
    private int idE;
    /**
     * Creates new form DlgRechercheTemoignages
     */
    public DlgRechercheTemoignages(int idE)
    {
        initComponents();
        this.recherche = "";
        this.regroupement = 0;
        this.regroupementEnAttente = 0;
        this.idE = idE;
        this.initialiser();
    }

    private void initialiser()
    {
        this.Ponderation.setValue(1);
        this.MotRecherche.setText("");
        this.Et.setSelected(true);
        this.MotExact.setSelected(true);
        this.NonSensibleCasse.setSelected(true);
        this.Recherche.setText(this.recherche);
        if(!this.recherche.equals(""))
            this.MotLiaisonInvisible.setVisible(true);
        else
            this.MotLiaisonInvisible.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TypeRecherche = new javax.swing.ButtonGroup();
        MotLiaison = new javax.swing.ButtonGroup();
        Casse = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Annuler = new javax.swing.JButton();
        Valider = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        MotsRecherches = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        CommencerRegroupement = new javax.swing.JButton();
        FinirRegroupement = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Recherche = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        MotRecherche = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Ponderation = new javax.swing.JSpinner();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        SensibleCasse = new javax.swing.JRadioButton();
        NonSensibleCasse = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        MotExact = new javax.swing.JRadioButton();
        Racine = new javax.swing.JRadioButton();
        ProcheOrtho = new javax.swing.JRadioButton();
        ProcheSonorite = new javax.swing.JRadioButton();
        MotLiaisonInvisible = new javax.swing.JPanel();
        Et = new javax.swing.JRadioButton();
        Ou = new javax.swing.JRadioButton();
        Pres = new javax.swing.JRadioButton();
        Accumulation = new javax.swing.JRadioButton();
        Soustraction = new javax.swing.JRadioButton();
        AjoutMot = new javax.swing.JButton();

        setTitle("Recherche de témoignages");

        jPanel1.setBackground(new java.awt.Color(226, 220, 207));
        jPanel1.setLayout(new java.awt.GridLayout(1, 2));

        Annuler.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        Annuler.setText("Annuler");
        Annuler.setPreferredSize(new java.awt.Dimension(109, 40));
        Annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnulerActionPerformed(evt);
            }
        });
        jPanel1.add(Annuler);

        Valider.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        Valider.setText("Lancer la recherche");
        Valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValiderActionPerformed(evt);
            }
        });
        jPanel1.add(Valider);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setBackground(new java.awt.Color(226, 220, 207));
        jPanel2.setLayout(new java.awt.GridLayout(1, 2));

        MotsRecherches.setBackground(new java.awt.Color(226, 220, 207));
        MotsRecherches.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(226, 220, 207));
        jPanel3.setLayout(new java.awt.GridLayout(1, 2));

        CommencerRegroupement.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        CommencerRegroupement.setText("Commencer un regroupement");
        CommencerRegroupement.setPreferredSize(new java.awt.Dimension(307, 40));
        CommencerRegroupement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CommencerRegroupementActionPerformed(evt);
            }
        });
        jPanel3.add(CommencerRegroupement);

        FinirRegroupement.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        FinirRegroupement.setText("Finir un regroupement");
        FinirRegroupement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinirRegroupementActionPerformed(evt);
            }
        });
        jPanel3.add(FinirRegroupement);

        MotsRecherches.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        Recherche.setColumns(20);
        Recherche.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        Recherche.setRows(5);
        Recherche.setEnabled(false);
        jScrollPane1.setViewportView(Recherche);

        MotsRecherches.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.add(MotsRecherches);

        jPanel4.setBackground(new java.awt.Color(226, 220, 207));
        jPanel4.setLayout(new java.awt.GridLayout(4, 4));

        jLabel3.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel3.setText("Mot à rechercher :");
        jPanel4.add(jLabel3);

        MotRecherche.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jPanel4.add(MotRecherche);

        jPanel6.setBackground(new java.awt.Color(226, 220, 207));
        jPanel6.setLayout(new java.awt.GridLayout(2, 1));

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel1.setText("Pondération :");
        jPanel6.add(jLabel1);

        Ponderation.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jPanel6.add(Ponderation);

        jPanel4.add(jPanel6);

        jPanel7.setBackground(new java.awt.Color(226, 220, 207));
        jPanel7.setLayout(new java.awt.GridLayout(2, 1));

        jLabel2.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel2.setText("Sensible à la casse :");
        jPanel7.add(jLabel2);

        jPanel8.setBackground(new java.awt.Color(226, 220, 207));
        jPanel8.setLayout(new java.awt.GridLayout(1, 2));

        SensibleCasse.setBackground(new java.awt.Color(226, 220, 207));
        Casse.add(SensibleCasse);
        SensibleCasse.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        SensibleCasse.setText("Oui");
        SensibleCasse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel8.add(SensibleCasse);

        NonSensibleCasse.setBackground(new java.awt.Color(226, 220, 207));
        Casse.add(NonSensibleCasse);
        NonSensibleCasse.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        NonSensibleCasse.setText("Non");
        jPanel8.add(NonSensibleCasse);

        jPanel7.add(jPanel8);

        jPanel4.add(jPanel7);

        jLabel4.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel4.setText("Type de recherche :");
        jPanel4.add(jLabel4);

        jPanel5.setBackground(new java.awt.Color(226, 220, 207));
        jPanel5.setLayout(new java.awt.GridLayout(4, 1));

        MotExact.setBackground(new java.awt.Color(226, 220, 207));
        TypeRecherche.add(MotExact);
        MotExact.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        MotExact.setText("Mot exact");
        jPanel5.add(MotExact);

        Racine.setBackground(new java.awt.Color(226, 220, 207));
        TypeRecherche.add(Racine);
        Racine.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        Racine.setText("Racine");
        jPanel5.add(Racine);

        ProcheOrtho.setBackground(new java.awt.Color(226, 220, 207));
        TypeRecherche.add(ProcheOrtho);
        ProcheOrtho.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        ProcheOrtho.setText("Proche orthographiquement");
        jPanel5.add(ProcheOrtho);

        ProcheSonorite.setBackground(new java.awt.Color(226, 220, 207));
        TypeRecherche.add(ProcheSonorite);
        ProcheSonorite.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        ProcheSonorite.setText("Sonorité proche");
        jPanel5.add(ProcheSonorite);

        jPanel4.add(jPanel5);

        MotLiaisonInvisible.setBackground(new java.awt.Color(226, 220, 207));
        MotLiaisonInvisible.setLayout(new java.awt.GridLayout(5, 1));

        Et.setBackground(new java.awt.Color(226, 220, 207));
        MotLiaison.add(Et);
        Et.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        Et.setText("Et");
        MotLiaisonInvisible.add(Et);

        Ou.setBackground(new java.awt.Color(226, 220, 207));
        MotLiaison.add(Ou);
        Ou.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        Ou.setText("Ou");
        MotLiaisonInvisible.add(Ou);

        Pres.setBackground(new java.awt.Color(226, 220, 207));
        MotLiaison.add(Pres);
        Pres.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        Pres.setText("Près de");
        MotLiaisonInvisible.add(Pres);

        Accumulation.setBackground(new java.awt.Color(226, 220, 207));
        MotLiaison.add(Accumulation);
        Accumulation.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        Accumulation.setText("Accumulation");
        MotLiaisonInvisible.add(Accumulation);

        Soustraction.setBackground(new java.awt.Color(226, 220, 207));
        MotLiaison.add(Soustraction);
        Soustraction.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        Soustraction.setText("Soustraction");
        MotLiaisonInvisible.add(Soustraction);

        jPanel4.add(MotLiaisonInvisible);

        AjoutMot.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        AjoutMot.setText("Ajouter ce mot");
        AjoutMot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjoutMotActionPerformed(evt);
            }
        });
        jPanel4.add(AjoutMot);

        jPanel2.add(jPanel4);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AnnulerActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_AnnulerActionPerformed
    {//GEN-HEADEREND:event_AnnulerActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_AnnulerActionPerformed

    private void CommencerRegroupementActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_CommencerRegroupementActionPerformed
    {//GEN-HEADEREND:event_CommencerRegroupementActionPerformed
        this.regroupementEnAttente++;
        this.Recherche.append(" (");
    }//GEN-LAST:event_CommencerRegroupementActionPerformed

    private void FinirRegroupementActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_FinirRegroupementActionPerformed
    {//GEN-HEADEREND:event_FinirRegroupementActionPerformed
        if(this.regroupement>0)
        {
            this.recherche += ")";
            this.Recherche.append(")");
            this.regroupement--;
        }
        else
            JOptionPane.showMessageDialog(null, "Il faut qu'un regroupement soit commencé et qu'au moins un mot "
                    + "soit placé depuis le début du regroupement pour pouvoir le fermer.", "Erreur", JOptionPane.INFORMATION_MESSAGE, null);
    }//GEN-LAST:event_FinirRegroupementActionPerformed

    private void AjoutMotActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_AjoutMotActionPerformed
    {//GEN-HEADEREND:event_AjoutMotActionPerformed
        boolean valide = true;
        String message = "Erreur :";
        if((int)this.Ponderation.getValue()<1)
        {
            valide = false;
            message += "\nLa pondération doit être un entier positif non nul";
        }
        if(this.MotRecherche.getText().equals(""))
        {
            valide = false;
            message += "\nIl faut entrer un mot à rechercher";
        }
        if(this.MotRecherche.getText().contains(" "))
        {
            valide = false;
            message += "\nLe mot à rechercher ne doit pas comporter d'espace";
        }
        if(valide)
        {
            String mot = this.MotRecherche.getText();
            //Ajout du mot de liaison
            if(!this.recherche.equals(""))
            {
                if(this.Et.isSelected())
                    this.recherche += " AND ";
                if(this.Ou.isSelected())
                    this.recherche += " OR ";
                if(this.Pres.isSelected())
                    this.recherche += " NEAR ";
                if(this.Accumulation.isSelected())
                    this.recherche += " ACCUM ";
                if(this.Soustraction.isSelected())
                    this.recherche += " MINUS ";
            }
            while(this.regroupementEnAttente>0)
            {
                this.recherche += "(";
                this.regroupementEnAttente--;
                this.regroupement++;
            }
            //Ajout du type de recheche
            if(this.Racine.isSelected())
                this.recherche += "$";
            if(this.ProcheOrtho.isSelected())
                this.recherche += "?";
            if(this.ProcheSonorite.isSelected())
                this.recherche += "!";
            //Si la casse doit être prise en compte, ou si le mot est un mot de liaison
            if(this.SensibleCasse.isSelected())
                mot = "{"+mot+"}";
            if(mot.equalsIgnoreCase("and") || mot.equalsIgnoreCase("or") || mot.equalsIgnoreCase("near") || 
                    mot.equalsIgnoreCase("accum") || mot.equalsIgnoreCase("minus"))
                mot = "{"+mot+"}";
            //Ajout du mot
            this.recherche += mot;
            //Ajout de la pondération
            if((int)this.Ponderation.getValue()>1)
                this.recherche += "*"+this.Ponderation.getValue();
            this.initialiser();
        }
        else
            JOptionPane.showMessageDialog(null, message, "Erreur", JOptionPane.INFORMATION_MESSAGE, null);
    }//GEN-LAST:event_AjoutMotActionPerformed

    private void ValiderActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ValiderActionPerformed
    {//GEN-HEADEREND:event_ValiderActionPerformed
        if(this.regroupement>0)
            JOptionPane.showMessageDialog(null, "Il faut terminer le regroupement avant de lancer la recherche.", "Erreur", JOptionPane.INFORMATION_MESSAGE, null);
        else
        {
            DlgResultatRechercheTemoignages dlg = new DlgResultatRechercheTemoignages(this.idE, this.recherche);
            dlg.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_ValiderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(DlgRechercheTemoignages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(DlgRechercheTemoignages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(DlgRechercheTemoignages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(DlgRechercheTemoignages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Accumulation;
    private javax.swing.JButton AjoutMot;
    private javax.swing.JButton Annuler;
    private javax.swing.ButtonGroup Casse;
    private javax.swing.JButton CommencerRegroupement;
    private javax.swing.JRadioButton Et;
    private javax.swing.JButton FinirRegroupement;
    private javax.swing.JRadioButton MotExact;
    private javax.swing.ButtonGroup MotLiaison;
    private javax.swing.JPanel MotLiaisonInvisible;
    private javax.swing.JTextField MotRecherche;
    private javax.swing.JPanel MotsRecherches;
    private javax.swing.JRadioButton NonSensibleCasse;
    private javax.swing.JRadioButton Ou;
    private javax.swing.JSpinner Ponderation;
    private javax.swing.JRadioButton Pres;
    private javax.swing.JRadioButton ProcheOrtho;
    private javax.swing.JRadioButton ProcheSonorite;
    private javax.swing.JRadioButton Racine;
    private javax.swing.JTextArea Recherche;
    private javax.swing.JRadioButton SensibleCasse;
    private javax.swing.JRadioButton Soustraction;
    private javax.swing.ButtonGroup TypeRecherche;
    private javax.swing.JButton Valider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
