/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.io.File;


/**
 *
 * @author Annabelle
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Enqueteurs = new javax.swing.JButton();
        Enquetes = new javax.swing.JButton();
        AjoutCrime = new javax.swing.JButton();
        VoirPersonnes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MENU");
        setBackground(new java.awt.Color(226, 220, 207));
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(new java.awt.GridLayout(4, 1));

        Enqueteurs.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        Enqueteurs.setText("Voir les enquêteurs");
        Enqueteurs.setPreferredSize(new java.awt.Dimension(350, 70));
        Enqueteurs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnqueteursActionPerformed(evt);
            }
        });
        getContentPane().add(Enqueteurs);

        Enquetes.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        Enquetes.setText("Voir les enquêtes");
        Enquetes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnquetesActionPerformed(evt);
            }
        });
        getContentPane().add(Enquetes);

        AjoutCrime.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        AjoutCrime.setText("Enregistrer un crime");
        AjoutCrime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjoutCrimeActionPerformed(evt);
            }
        });
        getContentPane().add(AjoutCrime);

        VoirPersonnes.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        VoirPersonnes.setText("Voir les personnes");
        VoirPersonnes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoirPersonnesActionPerformed(evt);
            }
        });
        getContentPane().add(VoirPersonnes);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EnqueteursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnqueteursActionPerformed
        DlgEnqueteurs dlgEnqueteurs = new DlgEnqueteurs();
        dlgEnqueteurs.setVisible(true);
    }//GEN-LAST:event_EnqueteursActionPerformed

    private void AjoutCrimeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_AjoutCrimeActionPerformed
    {//GEN-HEADEREND:event_AjoutCrimeActionPerformed
        DlgAjoutCrime dlgAjoutCrime = new DlgAjoutCrime();
        dlgAjoutCrime.setVisible(true);
    }//GEN-LAST:event_AjoutCrimeActionPerformed

    private void EnquetesActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_EnquetesActionPerformed
    {//GEN-HEADEREND:event_EnquetesActionPerformed
        DlgEnquetes dlgEnquetes = new DlgEnquetes();
        dlgEnquetes.setVisible(true);
    }//GEN-LAST:event_EnquetesActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowGainedFocus
    {//GEN-HEADEREND:event_formWindowGainedFocus
        File path = new File("temp/enqueteur/");
        if(path.exists())
        {
            File[] files = path.listFiles();
            if(files!=null)
            {
                for(int i=0; i<files.length; i++)
                    files[i].delete();
            }
        }
        else
            path.mkdir();
        //Preuves images
        path = new File("temp/image/");
        if(path.exists())
        {
            File[] files = path.listFiles();
            if(files!=null)
            {
                for(int i=0; i<files.length; i++)
                    files[i].delete();
            }
        }
        else
            path.mkdir();
        //Preuves audio
        path = new File("temp/audio/");
        if(path.exists())
        {
            File[] files = path.listFiles();
            if(files!=null)
            {
                for(int i=0; i<files.length; i++)
                    files[i].delete();
            }
        }
        else
            path.mkdir();
        //Preuves video
        path = new File("temp/video/");
        if(path.exists())
        {
            File[] files = path.listFiles();
            if(files!=null)
            {
                for(int i=0; i<files.length; i++)
                    files[i].delete();
            }
        }
        else
            path.mkdir();
        //Personnes
        path = new File("temp/personne/");
        if(path.exists())
        {
            File[] files = path.listFiles();
            if(files!=null)
            {
                for(int i=0; i<files.length; i++)
                    files[i].delete();
            }
        }
        else
            path.mkdir();
    }//GEN-LAST:event_formWindowGainedFocus

    private void VoirPersonnesActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_VoirPersonnesActionPerformed
    {//GEN-HEADEREND:event_VoirPersonnesActionPerformed
        DlgPersonnes dlg = new DlgPersonnes();
        dlg.setVisible(true);
    }//GEN-LAST:event_VoirPersonnesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AjoutCrime;
    private javax.swing.JButton Enquetes;
    private javax.swing.JButton Enqueteurs;
    private javax.swing.JButton VoirPersonnes;
    // End of variables declaration//GEN-END:variables
}
